#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

target="${AI_RULE_TARGET:-rule/ai.list}"
sources=(
  rule/upstream/blackmatrix7/OpenAI/OpenAI.list
  rule/upstream/EAlyce/OpenAI.list
  rule/upstream/blackmatrix7/Gemini/Gemini.list
  rule/ai-custom.list
)

for source in "${sources[@]}"; do
  if [ ! -f "$source" ]; then
    echo "AI rule source not found: $source" >&2
    exit 1
  fi
done

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT
body="$tmp_dir/ai-rules.body"
generated="$tmp_dir/ai.list"

awk 'NF && $0 !~ /^[[:space:]]*#/ { print }' "${sources[@]}" \
  | sed 's/\r$//' \
  | LC_ALL=C sort -u > "$body"

count_type() {
  awk -F ',' -v type="$1" '$1 == type { count++ } END { print count + 0 }' "$body"
}

total="$(wc -l < "$body" | tr -d ' ')"

{
  printf '# NAME: Aggregated AI\n'
  printf '# AUTHOR: anyforker\n'
  printf '# REPO: https://github.com/anyforker/Surge\n'
  printf '# GENERATED BY: scripts/build-ai-rule-set.sh\n'
  for source in "${sources[@]}"; do
    printf '# SOURCE: %s\n' "$source"
  done
  printf '# DOMAIN: %s\n' "$(count_type DOMAIN)"
  printf '# DOMAIN-KEYWORD: %s\n' "$(count_type DOMAIN-KEYWORD)"
  printf '# DOMAIN-SUFFIX: %s\n' "$(count_type DOMAIN-SUFFIX)"
  printf '# IP-ASN: %s\n' "$(count_type IP-ASN)"
  printf '# IP-CIDR: %s\n' "$(count_type IP-CIDR)"
  printf '# IP-CIDR6: %s\n' "$(count_type IP-CIDR6)"
  printf '# TOTAL: %s\n' "$total"
  printf '\n'
  awk '{ print }' "$body"
} > "$generated"

mkdir -p "$(dirname "$target")"
if [ -f "$target" ] && cmp -s "$generated" "$target"; then
  exit 0
fi

mv "$generated" "$target"
