#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

target="${EMBY_RULE_TARGET:-rule/emby.list}"
sources=(
  rule/upstream/blackmatrix7/Emby/Emby.list
  rule/emby-custom.list
)

for source in "${sources[@]}"; do
  if [ ! -f "$source" ]; then
    echo "Emby rule source not found: $source" >&2
    exit 1
  fi
done

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT
body="$tmp_dir/emby-rules.body"
generated="$tmp_dir/emby.list"

awk -F ',' '
  $1 == "DOMAIN" || $1 == "DOMAIN-SUFFIX" {
    domain = tolower($2)
    gsub(/^[[:space:]]+|[[:space:]]+$/, "", domain)
    if (domain ~ /^[a-z0-9._-]+$/) print $1 "," domain
  }
' "${sources[@]}" \
  | LC_ALL=C sort -u > "$body"

count_type() {
  awk -F ',' -v type="$1" '$1 == type { count++ } END { print count + 0 }' "$body"
}

total="$(wc -l < "$body" | tr -d ' ')"
if [ "$total" -eq 0 ]; then
  echo "Generated empty Emby rule set" >&2
  exit 1
fi

{
  printf '# NAME: Aggregated Emby\n'
  printf '# AUTHOR: anyforker\n'
  printf '# REPO: https://github.com/anyforker/Surge\n'
  printf '# GENERATED BY: scripts/build-emby-rule-set.sh\n'
  for source in "${sources[@]}"; do
    printf '# SOURCE: %s\n' "$source"
  done
  printf '# DOMAIN: %s\n' "$(count_type DOMAIN)"
  printf '# DOMAIN-SUFFIX: %s\n' "$(count_type DOMAIN-SUFFIX)"
  printf '# TOTAL: %s\n' "$total"
  printf '\n'
  awk '{ print }' "$body"
} > "$generated"

mkdir -p "$(dirname "$target")"
if [ -f "$target" ] && cmp -s "$generated" "$target"; then
  exit 0
fi

mv "$generated" "$target"
