#!/usr/bin/env bash
set -euo pipefail

source_url="${SOURCE_URL:-https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-porn.list}"
output_file="${OUTPUT_FILE:-rule/adult.list}"

tmp_file="$(mktemp)"
trap 'rm -f "$tmp_file"' EXIT

{
  printf '## Adult site rule set for Surge\n'
  printf '## Source: %s\n' "$source_url"
  printf '## Supplemental entries: adult creator platforms and adult TLDs not present in source\n'
  printf '## Generated by: scripts/sync-adult-list.sh\n'
  printf '## Format: Surge rule list\n'
  printf '\n'

  {
    curl -L --fail --silent --show-error --max-time 30 "$source_url" \
      | awk 'NF && $0 !~ /^#/ { if ($0 ~ /^\+\./) print substr($0,3); else print $0 }'

    printf '%s\n' \
      admireme.vip \
      fansly.com \
      fanvue.com \
      justfor.fans \
      loyalfans.com \
      onlyfans.com \
      sex \
      xxx
  } \
    | sed 's/[[:space:]]//g' \
    | awk 'NF && $0 ~ /^[A-Za-z0-9._-]+$/ { print tolower($0) }' \
    | sort -u \
    | awk '{ print "DOMAIN-SUFFIX," $0 }'
} > "$tmp_file"

mkdir -p "$(dirname "$output_file")"
mv "$tmp_file" "$output_file"
trap - EXIT
